site_name: "ADSeismic"
site_url: "https://ai4earth.github.io/adseismic"
site_description: 'ADSeismic: A High Performance Package for Automatic Differentiation (AD) based General Seismic Inversion'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'ADSeismic.jl'
repo_url: 'https://github.com/kailaix/ADSeismic.jl'
nav:
    - Overview: README.md
theme:
  name: 'material'
plugins:
  - mkdocs-jupyter:
      ignore: ["docs/examples/*/*.ipynb", "docs/examples/*/*/*.ipynb"]
